# sources:
# - https://www.youtube.com/watch?v=J9jKKeV1XVE&t=370s
# - https://www.implenton.com/get-an-ssl-certificate-for-the-php-apache-docker-image-variant-with-certbot

services:
  filesender:
    volumes:
      - ./docker/assets/etc/apache2/000-no-ssl-default.conf:/etc/apache2/sites-enabled/000-default.conf
  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt/certs:/etc/letsencrypt
      - ./letsencrypt/data:/data/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt -d "${SITE_URL}" --email "${EMAIL}" --agree-tos
